### ISSUE TITLE
Issues with passing tests and solution

### ISSUE THREAD

**Issue by jessenovotny** [learn-co-curriculum/react-props-lab#3]
Solution isn't working.

First, this and the past few lessons have been referencing the following script tag in index.html
<script src="bundle.js"></script>

No such file exists in any lab thus far.

Second, it doesn't seem that the challenge requires us to tamper with index.js but the script tag referencing this file is missing from index.html. Not a problem though. However once I add that script tag, I can't escape an error in index.js...
`Uncaught SyntaxError: Unexpected token <` from line 7 in index.js

Lastly, I could be wrong, but shouldn't Spaceship.js be Spaceship.jsx? 

So yea... even after cloning, switching to the solution branch, and adding the missing script tag for index.js, nothing is rendering.

**Comment by bhollan** [comment]
I had no such issues.

If you can link to a repo that's demonstrating this, that would help.

EDIT: Sorry, I thought you had this issue in testing.
When I run `python -m SimpleHTTPServer`, I get 2 404's in the console for `bundle.js` and no HTML.
Also, when I run `mocha.run()`, it says `passes: 0, failures: 0, duration: 0s` and nothing else.

cc: @aturkewi

**Comment by gj** [comment]
Thanks @jessenovotny + @bhollan !
