### ISSUE TITLE
"Default Props" link is moved/broken

### ISSUE THREAD

**Issue by kjleitz** [learn-co-curriculum/react-props-lab#6]
The "Default Props" link should probably lead to https://facebook.github.io/react/docs/typechecking-with-proptypes.html#default-prop-values since the current URL (https://facebook.github.io/react/docs/reusable-components.html#default-prop-values) actually redirects to https://facebook.github.io/react/docs/components-and-props.html (which does not mention default props at all).

**Comment by gj** [comment]
Fixed here: https://github.com/learn-co-curriculum/react-props-lab/pull/7

Thanks @kjleitz !
